"""
added user to updates tables

Revision ID: 2858c0da24a5
Revises: a8ff779eb2b9
Created Date: 2024-06-04 20:16:36.466315+01:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2858c0da24a5"
down_revision = "a8ff779eb2b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chapter_updates", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "chapter_updates", "users", ["user_id"], ["id"])
    op.add_column("section_updates", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "section_updates", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "section_updates", type_="foreignkey")
    op.drop_column("section_updates", "user_id")
    op.drop_constraint(None, "chapter_updates", type_="foreignkey")
    op.drop_column("chapter_updates", "user_id")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
