"""
added meetings tables

Revision ID: 6fde3b095160
Revises: de1a64ea4425
Created Date: 2024-06-05 19:50:21.538980+01:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6fde3b095160"
down_revision = "de1a64ea4425"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matrix_meetings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("zone", sa.String(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("agenda", sa.String(), nullable=True),
        sa.Column("minutes_link", sa.String(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "timezone('Europe/London', timezone('Europe/London', CURRENT_TIMESTAMP))",
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_matrix_meetings_id"),
        "matrix_meetings",
        ["id"],
        unique=False,
    )
    op.create_table(
        "zonal_team_meetings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("zone", sa.String(), nullable=False),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("agenda", sa.String(), nullable=True),
        sa.Column("minutes_link", sa.String(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "timezone('Europe/London', timezone('Europe/London', CURRENT_TIMESTAMP))",
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zonal_team_meetings_id"),
        "zonal_team_meetings",
        ["id"],
        unique=False,
    )
    op.create_table(
        "section_meetings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("meeting_date", sa.Date(), nullable=False),
        sa.Column("agenda", sa.String(), nullable=True),
        sa.Column("minutes_link", sa.String(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "timezone('Europe/London', timezone('Europe/London', CURRENT_TIMESTAMP))",
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["section.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_section_meetings_id"),
        "section_meetings",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_section_meetings_id"), table_name="section_meetings")
    op.drop_table("section_meetings")
    op.drop_index(op.f("ix_zonal_team_meetings_id"), table_name="zonal_team_meetings")
    op.drop_table("zonal_team_meetings")
    op.drop_index(op.f("ix_matrix_meetings_id"), table_name="matrix_meetings")
    op.drop_table("matrix_meetings")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
