"""
added natcom buddy to committee member table

Revision ID: f90f193cc111
Revises: 6ebfe599eb2f
Created Date: 2024-06-09 23:24:25.773196+01:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f90f193cc111"
down_revision = "6ebfe599eb2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema and/or data, creating a new revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "committee_members", sa.Column("natcom_buddy_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None, "committee_members", "users", ["natcom_buddy_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema and/or data back to the previous revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "committee_members", type_="foreignkey")
    op.drop_column("committee_members", "natcom_buddy_id")
    # ### end Alembic commands ###


def merge_upgrade_ops() -> None:
    """Merge upgrade operations from multiple branches."""
    pass


def merge_downgrade_ops() -> None:
    """Merge downgrade operations from multiple branches."""
    pass
